[[plugins]] # 補完
repo = 'Shougo/deoplete.nvim'
if = 'has("python3")'
on_event = 'InsertEnter'
depends = ['deoplete-lsp']
hook_source = '''
  call deoplete#custom#option({
      \ 'enable_at_startup'         :  1,
      \ 'auto_complete_delay'       :  0,
      \ 'ignore_case'               :  0,
      \ 'smart_case'                :  1,
      \ 'camel_case'                :  0,
      \ 'refresh_always'            :  0,
      \ 'max_list'                  :  1000,
      \ 'auto_complete_start_length':  1
      \ })

  call deoplete#custom#source('_', 'sorters', ['sorter_word'])
  call deoplete#custom#source('_', 'matchers', ['matcher_full_fuzzy']) " fuzzy matcher
  call deoplete#custom#source('buffer', 'mark', '[buffer]')
  call deoplete#custom#source('omni', 'mark', '[omni]')

  inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
  inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<S-TAB>"
  inoremap <expr><CR>  pumvisible() ? deoplete#close_popup() : "<CR>"

  if !has('nvim')
    call dein#add('roxma/nvim-yarp')
      call dein#add('roxma/vim-hug-neovim-rpc')
  endif
'''
on_i = 1

[[plugins]]
repo = 'Shougo/deoplete-lsp'
on_source = 'deoplete.nvim'
