[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = 'InsertEnter'
depends = ['denops.vim']
hook_source = '''
  call ddc#custom#patch_global('sources', ['nvim-lsp', 'around', 'nextword'])
  call ddc#custom#patch_global('sourceOptions', {
        \ 'nvim-lsp': {
          \ 'mark': 'L',
          \ 'forceCompletionPattern': '\.\w*|:\w*|->\w*',
        \ },
        \ 'around': {'mark': 'A'},
        \ 'nextword': {'mark': 'nextword'},
        \ '_': {
          \ 'matchers': ['matcher_head'],
          \ 'sorters': ['sorter_rank'],
        \ },
      \ })

  call ddc#custom#patch_global('sourceParams', {
      \ 'around': {'maxSize': 500},
      \ })

  inoremap <silent><expr> <TAB>
      \ ddc#map#pum_visible() ? '<C-n>' :
      \ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
      \ '<TAB>' : ddc#map#manual_complete()
  inoremap <expr><S-TAB>  ddc#map#pum_visible() ? '<C-p>' : '<C-h>'
  call ddc#enable()
'''
on_i = 1


[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
on_source = 'ddc.vim'

[[plugins]]
repo = 'statiolake/ddc-ale'
on_source = 'ddc.vim'
