##LANGS
[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
hook_add='''
let g:vim_json_syntax_conceal = 0
'''

[[plugins]] # terraform syntax highlight
repo = 'hashivim/vim-terraform'
hook_add = '''
let g:terraform_fmt_on_save = 1
'''

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace' #visualize not nesessary whitespace after character

[[plugins]]
repo = 'Shougo/neocomplcache'

[[plugins]]
repo = 'vim-airline/vim-airline' #Custom Airline
hook_add='''
let g:airline#extensions#tabline#formatter='unique_tail'
let g:airline_powerline_fonts=0
let g:airline#extensions#tabline#enabled = 1
nmap <C-p> <Plug>AirlineSelectPrevTab
nmap <C-n> <Plug>AirlineSelectNextTab
let g:airline#extensions#tabline#buffer_idx_mode = 1
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes' #to set ailrline theme
hook_add='''
"let g:airline_theme='minimalist'
'''

[[plugins]]
repo = 'Yggdroot/indentLine' #visualize indent
hook_add='''
let g:indentLine_enabled = 0
let g:indentLine_char = '|'
let g:indentLine_leadingSpaceEnabled = 2
let g:indentLine_leadingSpaceChar = '·'
'''

[[plugins]]
repo = 'cohama/lexima.vim' #support edit bucket

[[plugins]]
repo = 'airblade/vim-gitgutter' # visualize git diff

[[plugins]]
repo = 'osyo-manga/vim-over' # support replace

[[plugins]]
repo = 'simeji/winresizer' # support window resize

[[plugins]]
repo = 'rking/ag.vim' # to use Ag in vim

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'scrooloose/nerdtree' # display directory and file construct
hook_add='''
let g:NERDTreeShowBookmarks=1
let g:indentLine_fileTypeExclude = ["nerdtree"]
let g:NERDTreeShowHidden=1
'''

[[plugins]]
repo = 'liuchengxu/vista.vim'
hook_add='''
let g:vista_icon_indent = ["▸ ", ""]
let g:vista_echo_cursor_strategy="floating_win"
nnoremap vvl :Vista lcn<CR>
nnoremap vvf :Vista finder lcn<CR>
let g:vista_fzf_preview = ['right:50%']
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs' # nerd-tree-sync-tab

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim' # search file , buffer
hook_add='''
nnoremap s <Nop>
nnoremap sa :<C-u>CtrlP<CR>
nnoremap sb :<C-u>CtrlPBuffer<CR>
nnoremap sd :<C-u>CtrlPDir<CR>
nnoremap sf :<C-u>CtrlP<CR>
nnoremap sl :<C-u>CtrlPLine<CR>
nnoremap sm :<C-u>CtrlPMRUFiles<CR>
nnoremap sq :<C-u>CtrlPQuickfix<CR>
nnoremap ss :<C-u>CtrlPMixed<CR>
nnoremap st :<C-u>CtrlPTag<CR>

let g:ctrlp_map = '<Nop>'
let g:ctrlp_use_caching = 0
let g:ctrlp_show_hidden = 1
let g:ctrlp_match_window = 'bottom,order:btt,min:12,max:12,results:100'
'''

[[plugins]]
repo = 'dense-analysis/ale'
hook_add='''
let g:ale_linters = {'python': ['flake8']}
let g:ale_fixers = {'python': ['autopep8', 'black', 'isort']}

let g:ale_open_list = 0
let g:ale_fix_on_save = 1
let g:ale_sign_column_always = 1
'''

[[plugins]]
repo = 'ncm2/float-preview.nvim'
hook_source = '''
set completeopt-=preview
let g:float_preview#docked = 0
'''

[[plugins]]
repo = 'tpope/vim-fugitive' # git

[[plugins]]
repo = 'cocopon/iceberg.vim' #colorscheme

[[plugins]]
repo = 'trevordmiller/nova-vim'


[[plugins]]
repo = 'chrisbra/NrrwRgn'

[[plugins]]
repo = 'rhysd/git-messenger.vim'
