[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[pluins]]
repo = 'Shougo/neosnippet-snippets'

# Lang
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # Haml
repo  = 'tpope/vim-haml'
on_ft = 'haml'

[[plugins]] # Html5
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'myhere/vim-nodejs-complete'
on_ft = 'Node.js'

[[plugins]]
repo = 'moll/vim-node'
on_ft = 'vim-node'

#置換プレビュー
[[plugins]]
repo = 'osyo-manga/vim-over'

#末尾ホワイトスペースの可視化
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'js-indent-color'

[[plugins]] # Markdown
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown','mkd']
hook_add = '''
    let g:vim_markdown_frontmatter = 1
    let g:vim_markdown_math = 1
'''

[[plugins]] # Golang
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]] # Japanese doc
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'
hook_add = '''
    set helplang=ja,en
'''

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'davidhalter/jedi-vim'
depends = 'deoplete.nvim'
on_ft = 'python'

#[[plugins]]
#repo = 'lambdalisue/vim-pyenv'
#depends = 'davidhalter/jedi-vim'
#on_ft = 'python'

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'

[[plugins]]
repo = 'andviro/flake8-vim'
on_ft = 'python'

# Colors
[[plugins]] # hybrid
repo = 'w0ng/vim-hybrid'

[[plugins]] # solarized
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'freeo/vim-kalisi'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neocomplcache'


[[plugins]]
repo = 'AlessandroYorba/Sierra'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add='''
let g:airline_powerline_fonts=1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add='''
let g:airline_theme='minimalist'
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'cohama/lexima.vim'

#resize window
[[plugins]]
repo = 'simeji/winresizer'
