[[plugins]]
repo = 'Shougo/dein.vim' # package manager

[[plugins]]
repo = 'scrooloose/nerdtree' # display directory and file construct
hook_add='''
let NERDTreeShowHidden = 1
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs' # nerd-tree-sync-tab

[[plugins]]
repo = 'ryanoasis/vim-devicons' # display file icon

##LANGS
[[plugins]] # Haml
repo  = 'tpope/vim-haml'
on_ft = 'haml'

[[plugins]] # Html5
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # Markdown
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown','mkd']

[[plugins]] # Golang
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'davidhalter/jedi-vim' #python complitation for external library
depends = 'deoplete.nvim'
on_ft = 'python'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace' #visualize not nesessary whitespace after character

[[plugins]]
repo = 'Shougo/neocomplcache'

[[plugins]]
repo = 'vim-airline/vim-airline' #Custom Airline
hook_add='''
let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled = 1
nmap <C-p> <Plug>AirlineSelectPrevTab
nmap <C-n> <Plug>AirlineSelectNextTab
let g:airline#extensions#tabline#buffer_idx_mode = 1
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes' #to set ailrline theme

[[plugins]]
repo = 'Yggdroot/indentLine' #visualize indent
hook_add='''
let g:indentLine_enabled = 0
let g:indentLine_char = '|'
let g:indentLine_leadingSpaceEnabled = 2
let g:indentLine_leadingSpaceChar = '·'
'''

[[plugins]]
repo = 'cohama/lexima.vim' #support edit bucket

[[plugins]]
repo = 'airblade/vim-gitgutter' # visualize git diff

[[plugins]]
repo = 'osyo-manga/vim-over' # support replace

[[plugins]]
repo = 'simeji/winresizer' # support window resize

[[plugins]]
repo = 'rking/ag.vim' # to use Ag in vim

[[plugins]]
repo = 'cocopon/iceberg.vim' #colorscheme
