[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
    let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'
hook_source = '''
" racerバイナリ指定
let g:racer_cmd = "~/.cargo/bin/racer"
" rust本体のソースコードパス指定
let $RUST_SRC_PATH="/home/trsnium/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src"
'''


[[plugins]]
repo = 'scrooloose/nerdtree'

# Lang
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # Haml
repo  = 'tpope/vim-haml'
on_ft = 'haml'

[[plugins]] # Html5
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'myhere/vim-nodejs-complete'
on_ft = 'Node.js'

[[plugins]]
repo = 'moll/vim-node'
on_ft = 'vim-node'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'js-indent-color'

[[plugins]] # Markdown
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown','mkd']
hook_add = '''
    let g:vim_markdown_frontmatter = 1
    let g:vim_markdown_math = 1
'''

[[plugins]] # Golang
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]] # Japanese doc
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'
hook_add = '''
    set helplang=ja,en
'''

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

#[[plugins]]
#repo = 'lambdalisue/vim-pyenv'
#depends = 'davidhalter/jedi-vim'
#on_ft = 'python'

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'

[[plugins]]
repo = 'andviro/flake8-vim'
on_ft = 'python'

# Colors
[[plugins]] # hybrid
repo = 'w0ng/vim-hybrid'

[[plugins]] # solarized
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'freeo/vim-kalisi'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neocomplcache'


[[plugins]]
repo = 'AlessandroYorba/Alduin'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Yggdroot/indentLine'
